Guest/urls.py
from django.urls import path
from Guest import views
app_name="Guest"

urlpatterns = [
    path('',views.index,name="index"),
    path('Login/',views.Login,name="Login"),
    path('Userreg/',views.Userreg,name="Userreg"),
    path('Ajaxplace/',views.Ajaxplace,name="Ajaxplace"),
    path('policereg/',views.policereg,name="policereg"),
    path('advocatereg/',views.advocatereg,name="advocatereg"),
]

MiniProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Admin/',include('Admin.urls')),
    path('Basics/',include('Basics.urls')),
    path('',include('Guest.urls')),
    path('User/',include('User.urls')),
    path('PoliceStation/',include('PoliceStation.urls')),
    path('Advocate/',include('Advocate.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views
app_name="User"

urlpatterns = [
    path('HomePage/',views.HomePage,name="HomePage"),
    path('Logout/',views.Logout,name="Logout"),
    path('myprofile/',views.myprofile,name="myprofile"),
    path('EditProfile/',views.EditProfile,name="EditProfile"),
    path('changepwd/',views.changepwd,name="changepwd"),
    path('viewadvocates/',views.viewadvocates,name="viewadvocates"),
    path('booking/<int:lawid>/',views.booking,name="booking"),
    path('viewbooking/',views.viewbooking,name="viewbooking"),
    path('uploaddocs/<int:bid>/',views.uploaddocs,name="uploaddocs"),



    path('chatpage/<int:id>',views.chatpage,name="chatpage"),
    path('ajaxchat/',views.ajaxchat,name="ajaxchat"),
    path('ajaxchatview/',views.ajaxchatview,name="ajaxchatview"),
    path('clearchat/',views.clearchat,name="clearchat"),

    path('complaint/',views.complaint,name="complaint"),
    path('delete_complaint/<int:cid>/',views.delete_complaint,name="delete_complaint"),
]

User/models.py
from django.db import models
from Guest.models import*

# Create your models here.
class tbl_booking(models.Model):
    booking_date= models.DateField(auto_now_add=True)
    booking_status=models.IntegerField(default=0)
    booking_content=models.CharField(max_length=150)
    booking_file=models.FileField(upload_to="Assets/User/file")
    booking_amount=models.CharField(max_length=40)
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)
    advocate=models.ForeignKey(tbl_advocate,on_delete=models.CASCADE)


class tbl_chat(models.Model):
    
    chat_content = models.CharField(max_length=500)
    chat_time = models.DateTimeField()
    chat_file = models.FileField(upload_to='ChatFiles/')
    user_from = models.ForeignKey(tbl_user,on_delete=models.CASCADE,related_name="user_from",null=True)
    user_to = models.ForeignKey(tbl_user,on_delete=models.CASCADE,related_name="user_to",null=True)
    advocate_from = models.ForeignKey(tbl_advocate,on_delete=models.CASCADE,related_name="advocate_from",null=True)
    advocate_to = models.ForeignKey(tbl_advocate,on_delete=models.CASCADE,related_name="advocate_to",null=True)

class tbl_complaint(models.Model):
    complaint_date=models.DateField(auto_now_add=True)
    complaint_title=models.CharField(max_length=150)
    complaint_content=models.CharField(max_length=500)
    complaint_status=models.IntegerField(default=0)
    complaint_reply=models.CharField(max_length=500,null=True)
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)

User/views.py
from django.shortcuts import render,redirect
from Guest.models import*
from User.models import *
from datetime import datetime
from django.db.models import Q
# Create your views here.
def HomePage(request):
    return render(request,'User/HomePage.html')
def Logout(request):
    del request.session['uid']
    return redirect("Guest:Login")
def myprofile(request):
    userdata=tbl_user.objects.get(id=request.session['uid'])
    return render(request,'User/Myprofile.html',{'userdata':userdata})

def EditProfile(request):
    dis=tbl_district.objects.all()
    placename=tbl_place.objects.all()
    userdata=tbl_user.objects.get(id=request.session['uid'])
    if request.method=='POST':
        user_name=request.POST.get('txt_username')
        user_email=request.POST.get('txt_email')
        user_contact=request.POST.get('txt_contact')
        user_address=request.POST.get('txt_address')
        user_photo=request.FILES.get('txt_photo')
     
        place=tbl_place.objects.get(id=request.POST.get('sel_place'))
        userdata.user_name=user_name
        userdata.user_email=user_email
        userdata.user_contact=user_contact
        userdata.user_address=user_address
        userdata.user_photo=user_photo
        
        userdata.place=place
        userdata.save()
        return render(request,'User/EditProfile.html',{'msg':"updated"})
    else:

        return render(request,'User/EditProfile.html',{'userdata':userdata,'dis':dis,'data':placename})

def changepwd(request):
        userdata=tbl_user.objects.get(id=request.session['uid'])
        dbpass=userdata.user_password
        if request.method=='POST':
                old=request.POST.get('txt_oldpwd')
                new=request.POST.get('txt_newpwd')
                cpass=request.POST.get('txt_confirmpwd')
                if dbpass==old:
                        if new==cpass:
                                userdata.policestation_password=new
                                userdata.save()
                                return render(request,'User/Changepwd.html',{'msg':"password changed"})
                        else:
                                return render(request,'User/Changepwd.html',{'msg':"password does not match"}) 
                else:
                        return render(request,{'msg':"invalid old password"})  
        else:
                return render(request,'User/Changepwd.html')     
    



def viewadvocates(request):
    adv=tbl_advocate.objects.all()
    return render(request ,'User/Viewadvocates.html',{'adv':adv})

def booking(request,lawid):
    advocate=tbl_advocate.objects.get(id=lawid)
    user=tbl_user.objects.get(id=request.session['uid'])
    tbl_booking.objects.create(advocate=advocate,user=user)
    return render(request,'User/Viewadvocates.html',{'msg':"Booking Successful"})


def viewbooking(request):
      bookdata=tbl_booking.objects.filter(user=request.session['uid'])
      return render(request,'User/Mybooking.html',{'bookdata':bookdata})


def uploaddocs(request,bid):
    bookingdata=tbl_booking.objects.get(id=bid)
    if request.method=='POST':
        booking_docs=request.FILES.get('docfile')
        booking_content=request.POST.get('description')
        bookingdata.booking_content=booking_content
        bookingdata.booking_file=booking_docs
        bookingdata.booking_status=3
        bookingdata.save()
        return redirect('User:viewbooking')
    else:
        return render(request,'User/UploadDocs.html')


def chatpage(request,id):
    advocate  = tbl_advocate.objects.get(id=id)
    return render(request,"User/Chat.html",{"user":advocate})

def ajaxchat(request):
    from_user = tbl_user.objects.get(id=request.session["uid"])
    to_advocate = tbl_advocate.objects.get(id=request.POST.get("tid"))
    tbl_chat.objects.create(chat_content=request.POST.get("msg"),chat_time=datetime.now(),user_from=from_user,advocate_to=to_advocate,chat_file=request.FILES.get("file"))
    return render(request,"User/Chat.html")

def ajaxchatview(request):
    tid = request.GET.get("tid")
    user = tbl_user.objects.get(id=request.session["uid"])
    chat_data = tbl_chat.objects.filter((Q(user_from=user) | Q(user_to=user)) & (Q(advocate_from=tid) | Q(advocate_to=tid))).order_by('chat_time')
    return render(request,"User/ChatView.html",{"data":chat_data,"tid":int(tid)})

def clearchat(request):
    tbl_chat.objects.filter(Q(user_from=request.session["uid"]) & Q(advocate_to=request.GET.get("tid")) | (Q(advocate_from=request.GET.get("tid")) & Q(advocate_to=request.session["uid"]))).delete()
    return render(request,"User/ClearChat.html",{"msg":"Chat Deleted Sucessfully...."})


def complaint(request):
    complaints=tbl_complaint.objects.filter(user=request.session['uid'])
    if request.method=='POST':
        complaint_title=request.POST.get('txt_title')
        complaint_content=request.POST.get('txt_content')
        user=tbl_user.objects.get(id=request.session['uid'])
        tbl_complaint.objects.create(complaint_title=complaint_title,complaint_content=complaint_content,user=user)
        return render(request,'User/Complaint.html',{'msg':"Complaint Submitted"})
    else:
        return render(request,'User/Complaint.html',{'complaints':complaints})

def delete_complaint(request,cid):
    complaint=tbl_complaint.objects.get(id=cid)
    complaint.delete()
    return redirect('User:complaint')

User/templates/User/Chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="path/to/your/css/styles.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<style>
    .par-card{
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .head-sec {
        width: 840px;
        background-color: #6c8cfc;
        padding: 17px;
        border-radius: 10px;
        border-bottom: 1px solid white;
        margin-left: 8px;
        margin-top: 8px;
        display: flex;
        gap: 10px;
    }
    .content {
        display: flex;
        gap: 10px;
        width: 840px;
    }
    .option {
        color:white;
        font-size: 20px;
    }
    .option-content {
        width: 115px;
        padding: 10px;
        background-color: #90caf9;
        border-radius: 10px;
        position: absolute;
        left: 1036px;
        margin-top: 4px;
        display: none;
        transition: transform 3.9s ease-in-out;
    }
    .option-selection {
        display: flex;
        gap: 5px;
        flex-direction: column;
        align-items: center;
    }
    .con-card {
        width: 840px;
        padding: 24px;
        border-radius: 10px;
        background-color: transparent;
        min-height: 520px;
    }
    .message-card {
        padding: 24px;
        /* border-radius: 10px; */
        border-top: 1px solid white;
    }
    .message-box {
        padding: 10px;
        width: 750px;
        margin-left: 5px;
        border: none;
        background-color: #F5F5F5;
        border-radius: 10px;
    }
    .chat-card {
        /* background-color: #3f32f41c; */
        padding: 10px;
        box-shadow: 0 0 33px;
        border-radius: 10px;
    }
    .btn {
        background-color: transparent;
        border: none;
    }
    .ic-size {
        font-size: 20px;
        color: #6c8cfc;
    }
    .font {
        color: white;
        font-size: 20px;
        font-family: Poor Richard;
    }
    .r-mess {
        padding: 5px;
        background-color: #BBDEFB;
        border-radius: 10px;
        max-width: 555px;
        width: fit-content;
    }
    .s-mess {
        padding: 5px;
        background-color: #90caf9;
        border-radius: 10px;
        max-width: 555px;
        width: fit-content;
    }
    .par-r-mess {
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        padding-bottom: 5px;
    }
    .par-s-mess {
        display: flex;
        flex-direction: column;
        padding-bottom: 5px;
        align-items: flex-end;
    }
    .s-time {
        padding: 2px;
        font-size: 9px;
        display: flex;
        justify-content: flex-end;
    }
    .r-time {
        padding: 2px;
        font-size: 9px;
    }
    .con-width {
        min-width: 35px;
    }
    .scroll-con {
        overflow-y: scroll;
        height: 581px;
    }
    .scroll-con::-webkit-scrollbar {
      display: none;
    }


    .sk-folding-cube {
        margin: 20px auto;
        width: 40px;
        height: 40px;
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: rotateZ(45deg);
                transform: rotateZ(45deg);
    }

    .sk-folding-cube .sk-cube {
        float: left;
        width: 50%;
        height: 50%;
        position: relative;
        -webkit-transform: scale(1.1);
            -ms-transform: scale(1.1);
                transform: scale(1.1); 
    }
    .sk-folding-cube .sk-cube:before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #333;
        -webkit-animation: sk-foldCubeAngle 2.4s infinite linear both;
                animation: sk-foldCubeAngle 2.4s infinite linear both;
        -webkit-transform-origin: 100% 100%;
            -ms-transform-origin: 100% 100%;
                transform-origin: 100% 100%;
    }
    .sk-folding-cube .sk-cube2 {
        -webkit-transform: scale(1.1) rotateZ(90deg);
                transform: scale(1.1) rotateZ(90deg);
    }
    .sk-folding-cube .sk-cube3 {
        -webkit-transform: scale(1.1) rotateZ(180deg);
                transform: scale(1.1) rotateZ(180deg);
    }
    .sk-folding-cube .sk-cube4 {
        -webkit-transform: scale(1.1) rotateZ(270deg);
                transform: scale(1.1) rotateZ(270deg);
    }
    .sk-folding-cube .sk-cube2:before {
        -webkit-animation-delay: 0.3s;
                animation-delay: 0.3s;
    }
    .sk-folding-cube .sk-cube3:before {
        -webkit-animation-delay: 0.6s;
                animation-delay: 0.6s; 
    }
    .sk-folding-cube .sk-cube4:before {
        -webkit-animation-delay: 0.9s;
                animation-delay: 0.9s;
    }
    @-webkit-keyframes sk-foldCubeAngle {
        0%, 10% {
            -webkit-transform: perspective(140px) rotateX(-180deg);
                    transform: perspective(140px) rotateX(-180deg);
            opacity: 0; 
        } 25%, 75% {
            -webkit-transform: perspective(140px) rotateX(0deg);
                    transform: perspective(140px) rotateX(0deg);
            opacity: 1; 
        } 90%, 100% {
            -webkit-transform: perspective(140px) rotateY(180deg);
                    transform: perspective(140px) rotateY(180deg);
            opacity: 0; 
        } 
    }

    @keyframes sk-foldCubeAngle {
        0%, 10% {
            -webkit-transform: perspective(140px) rotateX(-180deg);
                    transform: perspective(140px) rotateX(-180deg);
            opacity: 0; 
        } 25%, 75% {
            -webkit-transform: perspective(140px) rotateX(0deg);
                    transform: perspective(140px) rotateX(0deg);
            opacity: 1; 
        } 90%, 100% {
            -webkit-transform: perspective(140px) rotateY(180deg);
                    transform: perspective(140px) rotateY(180deg);
            opacity: 0; 
        }
    }
    .blur-page {
        margin-top: -10px;
        height: 100%;
        width: 99%;
        background-color: rgba(255, 255, 255, 0.729);
        position: absolute;
    }
    .profile {
        display: none;
        width: 100%;
        background-color: #ffffffed;
        justify-content: center;
        align-items: center;
        height: 100vh;
        position: absolute;
        left: 0px;
        top: 0px;
    }
    .profile-close {
        display: flex;
        justify-content: flex-end;
        align-items: center;
    }
    .cl-ic {
        font-size: 27px;
        color: #d4d2d2;
    }
    .date-con {
        display: flex;
        justify-content: center;
        align-items: center;
        color: gray;
        font-size: 13px;
        margin-bottom: 10px;
    }
</style>
<body>
    <div class="blur-page" id="b-page">
        <div class="sk-folding-cube">
            <div class="sk-cube1 sk-cube"></div>
            <div class="sk-cube2 sk-cube"></div>
            <div class="sk-cube4 sk-cube"></div>
            <div class="sk-cube3 sk-cube"></div>
        </div>
    </div>
    <div class="profile" id="profile">
        <div>
            <div class="profile-close" onclick="close_profile()">
                <i class="fa-regular fa-circle-xmark cl-ic"></i>
            </div>
            <div>
                <img src="{{user.advocate_photo.url}}" width="300px" height="300px" alt="">
            </div>
        </div>
    </div>    
    <div class="par-card">
        <div class="chat-card">
            <div class="head-sec" id="changeable">
                <div class="content">
                    <div  onclick="open_profile()">
                        <img src="{{user.advocate_photo.url}}" width="40px" height="40px" style="border-radius: 50%;" alt="">
                    </div>
                    <div class="font">
                        {{user.advocate_name}}
                        <input type="hidden" name="txt_id" id="txt_id" value="{{user.id}}">
                    </div>
                </div>
                <div>
                    <button style="background-color: transparent;border: none;" onclick="handleOption()"><i class="fa-solid fa-ellipsis-vertical option"></i></button>
                </div>
            </div>
            <div class="option-content" id="option-div">
                <div class="option-selection">
                    <div><a  style="text-decoration: none;color: white;" onclick="clearchat()"><i class="fa-solid fa-broom"></i>&nbsp;Clear Chat</a></div>
                </div>
            </div>
           <div class="scroll-con" id="sc-down">
            <div class="con-card" id="conversation" onclick="date_see()">
            </div>
           </div>
            <div class="message-card">
                <label for="photo_data">
                    <i class="fas fa-paperclip ic-size"></i>
                </label>
                <input type="file" name="photo_data" id="photo_data" style="display: none;" onchange="sendChat('{{user.id}}')">
                <input type="text" name="txt_msg" class="message-box" id="txt_msg" placeholder="Type your message..." autocomplete="off">
                <button class="btn" type="submit" onclick="sendChat('{{user.id}}')"><i class="fas fa-paper-plane ic-size"></i></button>
            </div>
        </div>
    </div>
</body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
      document.getElementById("b-page").style.display = "none"
      document.getElementById("profile").style.display = "none"
      var dateval = false
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Check if this cookie string begins with the name we want
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }


    function sendChat(tid) {
        var msg = document.getElementById("txt_msg").value;
        var fileInput = document.getElementById("photo_data");
        var file = fileInput.files[0];
        if (msg.trim() === "" && !file)
        {

        }
        else
        {
            var fd = new FormData()
            fd.append("file",file)
            fd.append("tid",tid)
            fd.append("msg",msg)
            var ur = "{% url 'User:ajaxchat' %}"
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                type:'POST',
                url: ur,
                data: fd,
                processData: false,
                contentType: false,
                headers: { "X-CSRFToken": csrftoken }, // Include CSRF token in headers
                success: function (data) {
                    // $("#selplace").html(data);
                    document.getElementById('txt_msg').value = "" 
                    document.getElementById("photo_data").value = ""
                    $('#sc-down').animate({scrollTop: $('#sc-down')[0].scrollHeight});
                    var element = document.getElementById("sc-down");
                    element.scrollTop = element.scrollHeight - element.clientHeight;
                },
            });
        }
    };

    function viewChat() {
        var id = document.getElementById("txt_id").value
        var ur = "{% url 'User:ajaxchatview' %}"
        $.ajax({
            url: ur,
            data: { tid: id, },
            success: function (data) {
                $("#conversation").html(data);
            }
        });
    };

    viewChat()
    setInterval(viewChat,800)

    function handleOption() {
        let Check = document.getElementById('option-div')
        if(Check.style.display === "none" )
        document.getElementById("option-div").style.display = "block"
        else
        document.getElementById("option-div").style.display = "none"

    }

    function clearchat() {
        var id = document.getElementById("txt_id").value
        var ur = "{% url 'User:clearchat' %}"
        document.getElementById("b-page").style.display = "block"
        $.ajax({
            url: ur,
            data: { tid: id, },
            success: function (data) {
                // console.log(data);
                document.getElementById("b-page").style.display = "none"
                alert(data)
                location.reload()
            }
        });
    };

    function close_profile() {
        document.getElementById("profile").style.display = "none"
    }

    function open_profile() {
        document.getElementById("profile").style.display = "flex"
    }

</script>

User/templates/User/ClearChat.html
{{msg}}

User/templates/User/Header.html
"{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Lawmaker &mdash; Website Template by Colorlib</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'Templates/main/css/icomoon.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/magnific-popup.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'Templates/main/css/owl.theme.default.min.css' %}">
	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/flexslider.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'Templates/main/fonts/flaticon/font/flaticon.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'Templates/main/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'Templates/main/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'Templates/main/js /respond.min.js"></script>
	<![endif]-->



	</head>
	<body>
		
	<div class="ftco-loader"></div>
	
	<div id="page">
	<nav class="ftco-nav" role="navigation" style="background-color: black;">
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-md-2">
						<div id="ftco-logo"><a href="{% url 'User:HomePage' %}">Lawmaker</a></div>
					</div>
					<div class="col-md-10 text-right menu-1">
						<ul>
							<li class="active"><a href="{% url 'User:HomePage' %}">Home</a></li>
							<li><a href="{% url 'User:myprofile' %}">MyProfile</a></li>
							<li><a href="{% url 'User:viewadvocates' %}">View Advocates</a></li>
							<li><a href="{% url 'User:viewbooking' %}">View Booking</a></li>
							<li><a href="{% url 'User:complaint' %}">Complaints</a></li>
							<li><a href="{% url 'User:Logout' %}">LogOut</a></li>
							
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</nav>
    <div style="padding-top: 150px;padding-bottom: 50px;" align="center">

    {% block content %}
    {% endblock %}

    </div>
	<footer id="ftco-footer" role="contentinfo">
		<div class="container">
			<div class="row row-pb-md">
				<div class="col-md-3 ftco-widget">
					<h4>Lawfirm</h4>
					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
				</div>
				<div class="col-md-3 col-md-push-1">
					<h4>Navigation</h4>
					<ul class="ftco-footer-links">
						<li><a href="#">Home</a></li>
						<li><a href="#">Practice Areas</a></li>
						<li><a href="#">Won Cases</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">About us</a></li>
					</ul>
				</div>

				<div class="col-md-3 col-md-push-1">
					<h4>Contact Information</h4>
					<ul class="ftco-footer-links">
						<li>198 West 21th Street, <br> Suite 721 New York NY 10016</li>
						<li><a href="tel://1234567920">+ 1235 2355 98</a></li>
						<li><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
					</ul>
				</div>

				<div class="col-md-3 col-md-push-1">
					<h4>Opening Hours</h4>
					<ul class="ftco-footer-links">
						<li>Mon - Thu: 9:00 - 21 00</li>
						<li>Fri 8:00 - 21 00</li>
						<li>Sat 9:30 - 15: 00</li>
					</ul>
				</div>

			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
					<p>
						<ul class="ftco-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</p>
				</div>
			</div>

		</div>
	</footer>
	</div>

	<div class="gototop js-top">
		<a href="#" class="js -gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'Templates/main/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'Templates/main/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'Templates/main/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'Templates/main/js/jquery.waypoints.min.js' %}"></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'Templates/main/js/jquery.stellar.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'Templates/main/js/owl.carousel.min.js' %}"></script>
	<!-- Flexslider -->
	<script src="{% static 'Templates/main/js/jquery.flexslider-min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'Templates/main/js/jquery.countTo.js' %}"></script>
	<!-- Magnific Popup -->
	<script src="{% static 'Templates/main/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'Templates/main/js/magnific-popup-options.js' %}"></script>
	<!-- Main -->
	<script src="{% static 'Templates/main/js/main.js' %}"></script>

	 <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

	</body>
</html>